# Generated by Django 5.0.4 on 2024-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstatus',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='productstatus',
            name='not_approved',
        ),
        migrations.AddField(
            model_name='productstatus',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255),
        ),
    ]
